-- MySQL Script generated by MySQL Workbench
-- Sat Sep 19 17:00:29 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`UserRole`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UserRole` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(55) NOT NULL,
  `Description` VARCHAR(255) NOT NULL,
  `IsOwner` BIT NOT NULL,
  `CanEditSystems` BIT NOT NULL COMMENT 'Edit, Remove and Make Products, Categories, Types, Status',
  `CanEditOrders` BIT NOT NULL,
  `CanSetOrdersStatus` BIT NOT NULL,
  `CanSetToPickUpStatus` BIT NOT NULL,
  `CanSetProductStock` BIT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(255) NOT NULL,
  `Name` VARCHAR(255) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `PasswordHash` VARCHAR(255) NOT NULL,
  `CreationDate` DATETIME NOT NULL,
  `isDeleted` BIT NOT NULL DEFAULT 0,
  `DeletedDate` DATETIME NULL DEFAULT NULL,
  `UserRole_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_User_UserRole1_idx` (`UserRole_ID` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC) VISIBLE,
  CONSTRAINT `fk_User_UserRole1`
    FOREIGN KEY (`UserRole_ID`)
    REFERENCES `mydb`.`UserRole` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ReservationStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ReservationStatus` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `Description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservation` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Date` DATETIME NOT NULL,
  `ReservationStatus_ID` INT NOT NULL,
  `User_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Reservation_ReservationStatus1_idx` (`ReservationStatus_ID` ASC) VISIBLE,
  INDEX `fk_Reservation_User1_idx` (`User_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Reservation_ReservationStatus1`
    FOREIGN KEY (`ReservationStatus_ID`)
    REFERENCES `mydb`.`ReservationStatus` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_User1`
    FOREIGN KEY (`User_ID`)
    REFERENCES `mydb`.`User` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PickupStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PickupStatus` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PaymentStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PaymentStatus` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL,
  `Description` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrderStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrderStatus` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrderType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrderType` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Table` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TableNum` INT NOT NULL,
  `Capacity` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `TableNum_UNIQUE` (`TableNum` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TotalPrice` DECIMAL(10,2) NOT NULL,
  `Payments` DECIMAL(10,2) NOT NULL,
  `TotalBalance` DECIMAL(10,2) NOT NULL,
  `CreationDate` DATETIME NOT NULL,
  `PaymentStatus_ID` INT NOT NULL,
  `OrderStatus_ID` INT NOT NULL,
  `OrderType_ID` INT NOT NULL,
  `Table_ID` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Order_PaymentStatus1_idx` (`PaymentStatus_ID` ASC) VISIBLE,
  INDEX `fk_Order_OrderStatus1_idx` (`OrderStatus_ID` ASC) VISIBLE,
  INDEX `fk_Order_OrderType1_idx` (`OrderType_ID` ASC) VISIBLE,
  INDEX `fk_Order_Table1_idx` (`Table_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Order_PaymentStatus1`
    FOREIGN KEY (`PaymentStatus_ID`)
    REFERENCES `mydb`.`PaymentStatus` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_OrderStatus1`
    FOREIGN KEY (`OrderStatus_ID`)
    REFERENCES `mydb`.`OrderStatus` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_OrderType1`
    FOREIGN KEY (`OrderType_ID`)
    REFERENCES `mydb`.`OrderType` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Table1`
    FOREIGN KEY (`Table_ID`)
    REFERENCES `mydb`.`Table` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ToPickUp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ToPickUp` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Address` VARCHAR(255) NOT NULL,
  `CreationTime` DATETIME NOT NULL,
  `CompletedTime` DATETIME NULL,
  `PickupStatus_ID` INT NOT NULL,
  `User_ID` INT NOT NULL,
  `Order_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_ToPickUp_PickupStatus1_idx` (`PickupStatus_ID` ASC) VISIBLE,
  INDEX `fk_ToPickUp_User1_idx` (`User_ID` ASC) VISIBLE,
  INDEX `fk_ToPickUp_Order1_idx` (`Order_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ToPickUp_PickupStatus1`
    FOREIGN KEY (`PickupStatus_ID`)
    REFERENCES `mydb`.`PickupStatus` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ToPickUp_User1`
    FOREIGN KEY (`User_ID`)
    REFERENCES `mydb`.`User` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ToPickUp_Order1`
    FOREIGN KEY (`Order_ID`)
    REFERENCES `mydb`.`Order` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PaymentType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PaymentType` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Receipt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Receipt` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PaymentAmount` DECIMAL(10,2) NOT NULL,
  `Datetime` DATETIME NOT NULL,
  `PaymentType_ID` INT NOT NULL,
  `Order_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Receipt_PaymentType1_idx` (`PaymentType_ID` ASC) VISIBLE,
  INDEX `fk_Receipt_Order1_idx` (`Order_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Receipt_PaymentType1`
    FOREIGN KEY (`PaymentType_ID`)
    REFERENCES `mydb`.`PaymentType` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Receipt_Order1`
    FOREIGN KEY (`Order_ID`)
    REFERENCES `mydb`.`Order` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProductType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProductType` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `Description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `Description` VARCHAR(255) NOT NULL,
  `Stock` INT NOT NULL COMMENT 'In Stock - Out Of Stock',
  `Price` DECIMAL(10,2) NOT NULL,
  `ProductType_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Product_ProductType1_idx` (`ProductType_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Product_ProductType1`
    FOREIGN KEY (`ProductType_ID`)
    REFERENCES `mydb`.`ProductType` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrderDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrderDetail` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(255) NOT NULL,
  `Product_ID` INT NOT NULL,
  `Order_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_OrderDetail_Product1_idx` (`Product_ID` ASC) VISIBLE,
  INDEX `fk_OrderDetail_Order1_idx` (`Order_ID` ASC) VISIBLE,
  CONSTRAINT `fk_OrderDetail_Product1`
    FOREIGN KEY (`Product_ID`)
    REFERENCES `mydb`.`Product` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderDetail_Order1`
    FOREIGN KEY (`Order_ID`)
    REFERENCES `mydb`.`Order` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrderModifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrderModifications` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(255) NOT NULL,
  `Date` DATETIME NOT NULL,
  `User_ID` INT NOT NULL,
  `Order_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_OrderModifications_User1_idx` (`User_ID` ASC) VISIBLE,
  INDEX `fk_OrderModifications_Order1_idx` (`Order_ID` ASC) VISIBLE,
  CONSTRAINT `fk_OrderModifications_User1`
    FOREIGN KEY (`User_ID`)
    REFERENCES `mydb`.`User` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderModifications_Order1`
    FOREIGN KEY (`Order_ID`)
    REFERENCES `mydb`.`Order` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ModificationsHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ModificationsHistory` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(255) NULL,
  `Date` DATETIME NULL,
  `User_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_ModificationsHistory_User1_idx` (`User_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ModificationsHistory_User1`
    FOREIGN KEY (`User_ID`)
    REFERENCES `mydb`.`User` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservation_has_Table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservation_has_Table` (
  `Reservation_ID` INT NOT NULL,
  `Table_ID` INT NOT NULL,
  PRIMARY KEY (`Reservation_ID`, `Table_ID`),
  INDEX `fk_Reservation_has_Table_Table1_idx` (`Table_ID` ASC) VISIBLE,
  INDEX `fk_Reservation_has_Table_Reservation1_idx` (`Reservation_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Reservation_has_Table_Reservation1`
    FOREIGN KEY (`Reservation_ID`)
    REFERENCES `mydb`.`Reservation` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_has_Table_Table1`
    FOREIGN KEY (`Table_ID`)
    REFERENCES `mydb`.`Table` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
